on: [push]

jobs:
  test-file-field-compare:
    runs-on: ubuntu-latest
    name: test-csv-files
    steps:
      - name: prepare-test-csv-files
        run: |
          echo "field1,field2,field3" > test_file.csv
          echo "0.0,1.0,2.0" >> test_file.csv
          echo "field1,field2,field3" > test_reference_file.csv
          echo "1e-12,1.0,2.0" >> test_reference_file.csv
          echo "field1,field2,field3" > test_reference_file_high_deviation.csv
          echo "1e-3,1.0,2.0" >> test_reference_file_high_deviation.csv
          echo "field1,field2" > test_reference_file_missing_field.csv
          echo "1e-12,1.0" >> test_reference_file_missing_field.csv

      - name: compare-test-files
        uses: dglaeser/action-field-compare@v1.0
        with:
          result: "test_file.csv"
          reference: "test_reference_file.csv"

      - name: compare-with-high-tolerance
        uses: dglaeser/action-field-compare@v1.0
        with:
          result: "test_file.csv"
          reference: "test_reference_file_high_deviation.csv"
          cli-options: "-rtol 1e-2 -atol 1e-2"

      - name: compare-with-ignoring-missing-reference-field
        uses: dglaeser/action-field-compare@v1.0
        with:
          result: "test_file.csv"
          reference: "test_reference_file_missing_field.csv"
          cli-options: "--ignore-missing-reference-fields"

      - name: compare-with-ignoring-missing-results-field
        uses: dglaeser/action-field-compare@v1.0
        with:
          result: "test_reference_file_missing_field.csv"
          reference: "test_file.csv"
          cli-options: "--ignore-missing-result-fields"

      - name: compare-with-excluded-fields
        uses: dglaeser/action-field-compare@v1.0
        with:
          result: "test_file.csv"
          reference: "test_reference_file_high_deviation.csv"
          cli-options: "--exclude-fields field1"

      - name: compare-selected-fields
        uses: dglaeser/action-field-compare@v1.0
        with:
          result: "test_file.csv"
          reference: "test_reference_file_high_deviation.csv"
          cli-options: "--include-fields field2 --include-fields field3"

      - name: prepare-test-folders
        run: |
          mkdir test_data
          cp test_file.csv test_data
          cp test_file.csv test_data/test_file_2.csv
          mkdir reference_data
          cp test_reference_file.csv reference_data/test_file.csv
          cp test_reference_file_high_deviation.csv reference_data/test_file_2.csv
          mkdir reference_data_additional_files
          cp reference_data/* reference_data_additional_files/
          cp reference_data_additional_files/test_file.csv reference_data_additional_files/test_file_3.csv

      - name: compare-folders
        uses: dglaeser/action-field-compare@v1.0
        with:
          result: "test_data"
          reference: "test_data"

      - name: compare-folders-with-high-tolerance
        uses: dglaeser/action-field-compare@v1.0
        with:
          result: "test_data"
          reference: "reference_data"
          cli-options: "-rtol 1e-2 -atol 1e-2"

      - name: compare-folders-with-file-inclusion-filter
        uses: dglaeser/action-field-compare@v1.0
        with:
          result: "test_data"
          reference: "reference_data"
          cli-options: "--include-files test_file.csv"

      - name: compare-folders-with-ignoring-missing-result-files
        uses: dglaeser/action-field-compare@v1.0
        with:
          result: "test_data"
          reference: "reference_data_additional_files"
          cli-options: "--ignore-missing-result-files -rtol 1e-2 -atol 1e-2"

      - name: compare-folders-with-ignoring-missing-reference-files
        uses: dglaeser/action-field-compare@v1.0
        with:
          result: "reference_data_additional_files"
          reference: "test_data"
          cli-options: "--ignore-missing-reference-files -rtol 1e-2 -atol 1e-2"
