on: [push]

jobs:
  test-file-field-compare:
    runs-on: ubuntu-latest
    name: test-csv-files
    steps:
      - name: prepare-test-csv-files
        run: |
          echo "field1,field2,field3" > test_file.csv
          echo "0.0,1.0,2.0" >> test_file.csv
          echo "field1,field2,field3" > test_reference_file.csv
          echo "1e-8,1.0,2.0" >> test_reference_file.csv
      
      - name: compare_test_files
        uses: dglaeser/action-field-compare@4da77b9f8b6b9cde36db97e2659f8d05cbeed8a0
        with:
          file: "test_file.csv"
          reference-file: "test_reference_file.csv"
