on: [push]

jobs:
  test-file-field-compare:
    runs-on: ubuntu-latest
    name: test-csv-files
    steps:
      - name: prepare-test-csv-files
        run: |
          echo "field1,field2,field3" > test_file.csv
          echo "0.0,1.0,2.0" >> test_file.csv
          echo "field1,field2,field3" > test_reference_file.csv
          echo "1e-12,1.0,2.0" >> test_reference_file.csv
          echo "field1,field2,field3" > test_reference_file_high_deviation.csv
          echo "1e-3,1.0,2.0" >> test_reference_file_high_deviation.csv

      - name: compare-test-files
        uses: dglaeser/action-field-compare@142227fc3744d78caf9e05e95465ed9dac05871f
        with:
          result: "test_file.csv"
          reference: "test_reference_file.csv"

      - name: compare-with-high-tolerance
        uses: dglaeser/action-field-compare@142227fc3744d78caf9e05e95465ed9dac05871f
        with:
          result: "test_file.csv"
          reference: "test_reference_file_high_deviation.csv"
          tolerance-options: "-rtol 1e-2 -atol 1e-2"

      - name: prepare-test-folders
        run: |
          mkdir test_data && cp test_file.csv test_data
          mkdir reference_data && cp test_reference_file_high_deviation.csv reference_data/test_file.csv

      - name: compare-folders
        uses: dglaeser/action-field-compare@142227fc3744d78caf9e05e95465ed9dac05871f
        with:
          result: "test_data"
          reference: "test_data"

      - name: compare-folders-with-high-tolerance
        uses: dglaeser/action-field-compare@142227fc3744d78caf9e05e95465ed9dac05871f
        with:
          result: "test_data"
          reference: "reference_data"
          tolerance-options: "-rtol 1e-2 -atol 1e-2"
